version: '3.8'

services:
  server:
    build: .
    restart: always
    ports:
      - 8080:8080
    depends_on:
      - mysqldb
    volumes:
      - tmpfs:/app/data

  mysqldb:
    image: mysql:8.0.33
    restart: always
    container_name: mysqldb
    ports:
      - 3307:3306
    environment:
      - MYSQL_DATABASE=logs
      - MYSQL_USER=assignment
      - MYSQL_PASSWORD=12345
      - MYSQL_ROOT_PASSWORD=12345

#  log_test:
#    build:
#      context: .
#      dockerfile: ./DockerFileTest
#    volumes:
#      - ./fire_requests.sh:/app/data/fire_requests.sh
#    restart: unless-stopped
#    depends_on:
#      - mysqldb
#      - server

volumes:
  tmpfs: