version: '3.8'

services:
  server:
    image: assignment:latest
#    build: .
    restart: always
    ports:
      - 8080:8080
    depends_on:
      - mysqldb
    volumes:
      - type: volume
        source: mydata
        target: /data
        volume:
          nocopy: true

  #    environment:
#      - MYSQL_ROOT_PASSWORD=$MYSQLDB_ROOT_PASSWORD
#      - MYSQL_DATABASE=$MYSQLDB_DATABASE
#      - MYSQL_USER=$MYSQLDB_USER
#      - SPRING_JPA_HIBERNATE_DDL_AUTO=update
#      - SPRING_DATASOURCE_URL=jdbc:mysql://mysqldb:3306/logs
  mysqldb:
    image: mysql:8.0.33
    restart: always
    container_name: mysqldb
    ports:
      - 3307:3306
    environment:
      - MYSQL_DATABASE=logs
      - MYSQL_USER=assignment
      - MYSQL_PASSWORD=12345
      - MYSQL_ROOT_PASSWORD=12345

volumes:
  mydata:

#    env_file: ./.env
#  maven:
#    image: "docker pull openjdk:17"
#  mysqldb:
#    image: mysql:8.0.33
#    restart: unless-stopped
#    env_file: ./.env
#    environment:
#      - MYSQL_ROOT_PASSWORD=$MYSQLDB_ROOT_PASSWORD
#      - MYSQL_DATABASE=$MYSQLDB_DATABASE
#    ports:
#      - $MYSQLDB_LOCAL_PORT:$MYSQLDB_DOCKER_PORT
#    volumes:
#      - db:/var/lib/mysql
#  app:
#    image: "mishalraj17/assignment-docker:latest"
#    depends_on:
#      - mysqldb
#    build: .
#    restart: on-failure
#    env_file: ./.env
#    ports:
#      - $SPRING_LOCAL_PORT:$SPRING_DOCKER_PORT
#    environment:
#      SPRING_APPLICATION_JSON: '{
#        "spring.datasource.url"  : "jdbc:mysql://mysqldb:$MYSQLDB_DOCKER_PORT/$MYSQLDB_DATABASE?useSSL=false",
#        "spring.datasource.username" : "$MYSQLDB_USER",
#        "spring.datasource.password" : "$MYSQLDB_ROOT_PASSWORD",
#        "spring.jpa.properties.hibernate.dialect" : "org.hibernate.dialect.MySQL5InnoDBDialect",
#        "spring.jpa.hibernate.ddl-auto" : "update"
#      }'
#    volumes:
#      - .m2:/root/.m2
#    stdin_open: true
#    tty: true
#
#volumes:
#  db: